### ISSUE TITLE
SE Onboarding task list

### ISSUE THREAD

**Issue by jccwm** [jccwm/Engineering-Leadership-Cert#1]
GitHub SE onboarding task list - for me to work through and learn - same as a new SE for product function and sales stories.
-------------------

We've organized this list in order of usefulness and immediacy, but please look through the whole list as you get started. Some things should be done in your first few days; the important stuff is right at the top. There are a bunch of optional reading materials and tools to install, so feel free to read articles as you find the time and become familiar with some of the tools as you find them useful. And if you're stuck or don't know what to do next, ask your buddy or any member of the SE team to point you in the right direction!

## [Who are we?](https://githubber.com/article/crafts/sales/sales-guide/sales-process/sales-culture)

- **We’re part of GitHub Sales, the public facing API for getting GitHub into your business**
- If a customer needs to interface with a human to help the buying process, we're here to help. No matter how big, no matter which product.
- We are the voice of the company.
- We trust our users.
- We are technical; technicality is a mindset, not a skill level.
- We file issues and, ideally, submit PR’s to fix an issue. If you see something, say something.

# Week 1

#### _Read these first!_  
**[How Solution Engineers Use GitHub](https://www.icloud.com/keynote/06-6dngfGgAMK168bBvYlAcYA#How_Solution_Engineers_use_GitHub)**   
[What, would you say, you do here?]( https://github.com/github/solutions-engineering/blob/master/README.md#what-we-do)  
[Guiding Principles for Technical Sales at GitHub](https://github.com/github/solutions-engineering/blob/master/guides/technical-selling-guiding-principles.md) 

### Tools and Services: Essentials pt. 1
We use many different tools to get our jobs done on the SE team. Below are some of the tools you'll use every day, so make sure you set these up right away.

* [ ] __[Okta](https://github.okta.com/)__ - Okta is a single sign-on tool that we use to provide GitHubbers access to Salesforce, AWS, GitHubberTV, BambooHR and others. Get an Okta account and set up two-factor authentication.

* [ ] __[Slack](https://github.slack.com/)__ - Slack is the chat application we use at GitHub. Download the desktop or mobile client from your app store of choice, or sign in from Okta. Once you're set up, [gif](http://giphy.com/) and [emoji](http://emoji.muan.co/) to your :heart:'s content!
  * You'll want to join the [`#solutions-engineering`](https://github.slack.com/archives/solutions-engineering) room immediately, and there are a number of other useful rooms as well. Ask your buddy for good rooms to lurk in! (Hubot 👇 hangs out in [`#solutions-eng-info`](https://github.slack.com/archives/solutions-eng-info)
  * You may also want to start familiarizing yourself with Hubot
  ![image of Hubot](https://avatars2.githubusercontent.com/u/5367660?s=20).  More on his surly ways can be found [here](https://hubot.github.com/) and how we use him can be found in the [Using Hubot GitHubber article](https://githubber.com/article/tools/chat/using-hubot).

* [ ] __[Halp](https://halp.githubapp.com)__ -  Halp is an internally-built ticketing system that we use to communicate with our customers. Customer-facing discussions about all sorts of topics happen here, from license requests to technical questions. Read more about Halp [here](https://github.com/github/sales/blob/master/guide/how-we-work.md#halp).

* [ ] __[Salesforce.com](https://github.my.salesforce.com)__ - sign in to [Okta](http://github.okta.com/) and you should see Salesforce (SFDC) listed as a work application. Click the Salesforce icon to automatically sign in to Salesforce. You'll use your Okta credentials to access Salesforce. We use SFDC to manage the forecasting data around leads and opportunities (close date, amount, next steps).

* [ ] __[ghe.io](http://ghe.io/)__ - GitHub's own internal instance of GitHub Enterprise. We use ghe.io for internal team blogs. The Sales Weekly, Enablement Weekly, and a few other departments post their internal blogs to https://ghe.io to keep our team and the entire company updated on important announcements, the numbers, new customers, and notable deals. Access ghe.io through [Okta](https://github.okta.com/). 

* [ ] __[Enterprise-Web](https://enterprise.github.com)__ - Sign in and authorize using the "GitHub" button, you should be staff. If not, please ask for help in the `#solutions-engineering`. From the customer's perspective, Enterprise Web is a portal where they can request a trial, download their license, access the latest release, and purchase seats. As GitHub staff, you'll have a CRM-esque view of our customers - trial requests, purchase history, custom agreement terms, and all active customer records are linked to Salesforce.
* [ ] __[Expensify](https://www.expensify.com/)__ - Expensify is used to track and submit expenses for reimbursement. The finance team has detailed articles on GitHubber on [what you can expense](https://githubber.com/article/benefits-and-policies/income/expenses) and [how to do it](https://githubber.com/article/benefits-and-policies/income/filing-an-expense-report). Access to this is available via [Okta](https://github.okta.com).

* [ ] __[Team](https://team.githubapp.com)__ - Keep up to date with goings-on at GitHub.
  * Be sure that your team profile is filled out with first and last name as well as your bio mentioning what team you're on! This is important for people to know who you are and how to interact with you.

* [ ] __[GitHubber.com](https://githubber.com)__ - The essential guide to life at GitHub. This should be covered in general onboarding, but lots of competitive information also lives here for us!

* [ ] __[GitHubber.tv](https://githubber.tv)__ - All sorts of useful and interesting videos live here, including office hours and TL;DR recordings.

- [ ] __[Looker](https://looker.com/)__ is our business intelligence tool and provides all kinds of valuable data and analytics. Log in via Okta by clicking this [link to Okta](https://github.okta.com/app/UserHome) and click the Looker app.  You will receive an error message but in order to grant you access, you will need to attempt to log in first. We'll come back to Looker later!

### Dealing with Notifications
Get ready for a tidal :ocean: of notifications coming your way! Part of life as a GitHubber is figuring out which notifications are important to you, and optimizing your workflow to see what you need to be aware of. There are two dominant schools of thought on the best way to look at your notifications: watching [__web notifications__](https://github.com/settings/notifications) or filtering __email notifications__. Choose your own adventure, or master both!  

__Remember, it's up to you to manage your notifications and find what's important! Unsubscribe and unwatch judiciously to keep a clean inbox, or let the notifications wash over you and keep your :eyes: on the important bits.__

#### For Email
Follow the instructions [here](https://githubber.com/article/crafts/sales/sales-guide/sales-tools/email) to setup gmail filters to help you manage your :mailbox: notifications. If in doubt, ask your teammates how they have filters set up.

**<DEPRECATED?>**
__Once your email filters are set up join the below Google Groups__
* [ ] fieldservices@github.com - [Google Groups](https://groups.google.com/a/github.com/forum/#!members/fieldservices)
* [ ] sf@github.com (if based in SF) - [request via Google Groups](https://groups.google.com/a/github.com/forum/#!members/sf)
* [ ] se-team@github.com - [request via Google Groups](https://groups.google.com/a/github.com/forum/#!members/se-team)
* [ ] se-emea-team@github.com (if based in EMEA) - [request via Google Groups](https://groups.google.com/a/github.com/forum/#!members/se-emea-team)

#### Repositories: Must Watch
* [ ] [solutions-engineering](https://github.com/github/solutions-engineering)
* [ ] [field-services](https://github.com/github/field-services)
* [ ] [knowledge-base](https://github.com/github/knowledge-base)

#### Repositories: Nice to Watch  
_Sign up and watch as much or as little as you want. There's *a lot* going on around here, don't feel like you must follow everything at the start_
* [ ] [sales](https://github.com/github/sales)
* [ ] [customer-feedback repository](https://github.com/github/customer-feedback)
* [ ] [sales-operations](https://github.com/github/sales-operations)  
* [ ] [enterprise repository](https://github.com/github/enterprise-releases)
* [ ] [marketing repository](https://github.com/github/marketing)
* [ ] [ent-web repository](https://github.com/github/enterprise-web)

#### Organizations to join

* [ ] [githubcustomers](https://github.com/githubcustomers) - Ask `@github/solutions-engineering` to add you.

#### Teams to Join ([GitHub.com Teams](https://github.com/orgs/github/teams/?query=sales))
Teams in GitHub have access to a specific set of repositories, and members get notified when the team is @ mentioned. Every Solutions Engineer should be a part of the following teams.
* [ ] [@github/solutions-engineering](https://github.com/orgs/github/teams/solutions-engineering)
* [ ] [@github/fieldservices](https://github.com/orgs/github/teams/fieldservices)
* [ ] [@github/sales](https://github.com/orgs/github/teams/sales)
* Inside Solutions Engineers should also be members of:
  * [ ] [@github/inside-solutions-engineering](https://github.com/orgs/github/teams/inside-solutions-engineering)
  * [ ] [@github/sales-corporate](https://github.com/orgs/github/teams/sales-corporate)
* Optional teams to join depending on region
  * [@github/solutions-engineering-americas](https://github.com/orgs/github/teams/solutions-engineering-americas)
  * [@github/solutions-engineering-emea](https://github.com/orgs/github/teams/solutions-engineering-emea)
  * [@github/solutions-engineering-apac](https://github.com/orgs/github/teams/solutions-engineering-apac)
  * [@github/channel-se](https://github.com/orgs/github/teams/channel-se)

### Bonus Reads
* [ ] [Rules for communicating at GitHub by @benbalter](http://ben.balter.com/2014/11/06/rules-of-communicating-at-github/)  
## Day 1-4

* [ ] Add your profile picture to the Solutions Engineering [README](https://github.com/github/solutions-engineering/blob/master/README.md)

### Guides pt. 1
Each of the guides in this checklist is an in-depth look at how we do things at GitHub. Take your time and explore, but don't be too concerned about knowing every bit of information here. It's more important to know where to find it when you need it than to keep it all in your head. Feel free to tackle these out of order.
* [ ] [Onboarding README](https://github.com/github/solutions-engineering/tree/master/guides/onboarding/README.md) - familiarize yourself with the on-boarding documentation. You will need to refer back to the ramp-up plan after completing this checklist.
* [ ] Peruse the [GitHub Guides](https://guides.github.com), especially:
  * [ ] [GitHub Flow](https://guides.github.com/introduction/flow/)  
  * [ ] [Hello World](https://guides.github.com/activities/hello-world/)  
  * [ ] [Forking](https://guides.github.com/activities/forking/)  
  * [ ] [Mastering Issues](https://guides.github.com/features/issues/)  
  * [ ] [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)
  * [ ] [GitHub Resources](https://resources.github.com/)
  * [ ] [GitHub Learning Lab](https://lab.github.com/)

### Tools and Services: Essentials pt. 2
* [ ] [Zoom](http://zoom.us/download) - We use Zoom extensively as our internal video conference tool. You'll want to install the desktop and mobile apps, and optionally install the extension for your browser of choice.
* [ ] [GitHub Desktop](http://desktop.github.com/)
* [ ] [Atom](https://atom.io/) - GitHub's open source text editor
* [ ] [LastPass](https://lastpass.com/) - Open an issue in the [Security Repository](https://github.com/github/security-iam/) to be invited to the SE LastPass Enterprise account. You'll receive a welcome email and have access to keys we share across the team, including AWS credentials and keys for Octodemo
  * [ ] Get access to shared Solutions Engineering LastPass folder
  * [ ] Get access to shared GitHub LastPass folders
* [ ] `.i am [USERNAME]` - In Slack, tell Hubot who you are so you get pings on your phone
* [ ] `.mac me <mac-address>` - In Slack, tell Hubot to keep track of where you are in HQ
* [ ] MS Office - Get access to Office 365 through [Gear](https://gear.githubapp.com), then login and download the suite
* [ ] [Strap](https://github.com/github/strap-internal) - Set up your new computer in the most GitHubby way possible
* [ ] [Caffeine](https://caffeine.en.softonic.com/mac) - A tiny program that prevents your Mac from automatically going to sleep, dimming the screen or starting screen savers.

### Email and Calendar
* [ ] Solutions Engineering calendar - We try to keep everyone's out of office and travel schedule in this calendar to coordinate across the team. Check out [this document](https://github.com/github/solutions-engineering/blob/master/calendar.md) for instructions on how to add this calendar.
* [ ] [Halp Unwatcher Chrome Extension](https://ghe.io/sachinr/halp-unwatcher) will install a button and keyboard shortcut to unwatch Halp threads directly from your email.

### Halp
* [ ] Review the Halp inboxes with your buddy
  * Sales - ESR
  * Sales - CSR
  * Sales - CSM
  * Sales - APAC
* [ ] Now that you're set up, review the [GitHubber Guide to Halp](https://githubber.com/category/tools/halp) for a walkthrough on its use.
* [ ] Using Halp, specifically setting reminders, @ mentioning, [Chrome Extension for Halp](https://github.com/github/halp-chrome) ([install using these instructions](https://github.com/github/sales/issues/2997#issue-153821182)), and cross linking.

__Halp labels to watch__
* [ ] [solutions-engineering Halp (Sales inbox) label](https://halp.githubapp.com/inboxes/sales/labels/solutions-engineering)
* [ ] [solutions-engineering Halp (Sales Corporate inbox) label](https://halp.githubapp.com/inboxes/sales-csr/labels/solutions-engineering)
* [ ] [solutions-engineering Halp (Sales Enterprise inbox) label](https://halp.githubapp.com/inboxes/sales-esr/labels/solutions-engineering)
* [ ] [solutions-engineering Halp (Sales CSM inbox) label](https://halp.githubapp.com/inboxes/sales-csm/labels/solutions-engineering)
* [ ] [solutions-engineering Halp (Sales APAC inbox) label](https://halp.githubapp.com/inboxes/sales-apac/labels/solutions-engineering)
* [ ] Custom Halp label with your GitHub handle created for each Sales inbox and followed - make sure to "Watch" your labels

#### GitHub partner organization and repositories
* [ ] Reach out to `@github/channel-team` to be invited to the [githubpartners](https://github.com/githubpartners) organization  
  * [ ] Request to join the [githubpartners/github-employees](https://github.com/orgs/githubpartners/teams/github-employees) team. Note that this is a secret team, so the link won't work until you've been added to the team.
  * [ ] Request to join the [githubpartners/github-solutions-engineering](https://github.com/orgs/githubpartners/teams/github-solutions-engineering) team
  * [ ] The [operations repo](https://github.com/githubpartners/operations) contains information and material accessible by *all* partners
  * [ ] Partner repositories like [this](https://github.com/githubpartners/macnica) contain *partner-specific* communication and issues *only*

#### Repositories - Other Internal Company Repositories
* https://github.com/github/docs (powers githubber.com)
* https://github.com/github/hr (all kinds of employee, benefits, and fun stuff being discussed)
* https://github.com/github/internal-jobs (see decisions around hiring, new roles)
* https://github.com/github/keynote (materials for producing good slide decks and presentations)
* https://github.com/github/product (the future of GitHub)
* https://github.com/github/releases (centralized conversations around GitHub releases)
* https://github.com/github/sanfrancisco (stuff around the office)
* https://github.com/github/gear (if you need gear, open issues here)

### Watch These!
* [ ] [Sales pitch](https://githubber.tv/github/github-pitch) by Michael King (~41 min)
* [ ] [Product demo](https://githubber.tv/github/demo-product) by Lee Faus (~44 min)

### Essential Reading
* [ ] [The Sales Craft](https://githubber.com/category/crafts/sales) - Who is Sales at GitHub? What do we do?
* [ ] [Sales Enablement Updates](https://pages.ghe.io/github/sales-enablement-updates/) - A weekly update on trainings and resources.
* [ ] [The GitHub Voice](https://githubber.com/article/crafts/writing/the-github-voice) - How to write the GitHub way.
* [ ] [Version Control Primer](https://githubber.com/article/crafts/sales/sales-guide/competition/version-control-primer) 

### Bonus Reads (and videos)
* [ ] [Background on Field Services Organization](https://github.com/github/inc/blob/master/_posts/2015-03-02-field-services.md)  
* [ ] Read [Sales Commission Plan](https://githubber.com/article/crafts/sales/sales-commission-plan)
* [ ] Read JPL's case study [JPL & GitHub](https://enterprise.github.com/case-studies/jpl)
* [ ] Watch [How NASA's JPL uses GitHub Enterprise](https://githubber.tv/github/collaboration-open-source-and-the-jpl-software-development-culture)   (~58 min)

# Week 2 and beyond
Now that you've got the basics out of the way, it's time to dive deep into what you'll be doing at GitHub. Below are resources that you'll continue to refer to as an SE at GitHub. Once you're done here, don't forget to look at the [Onboarding README](https://github.com/github/solutions-engineering/tree/master/guides/onboarding/README.md) to see what the rest of your ramp-up will look like.

* [ ] Get your buddy to introduce you to a few Hubbers from Sales (Development, Corporate, Enterprise, Customer Success) and ask them to shadow a few of their calls and demos for the next month or so. We want everyone to feel they can sit silently and listen into a call or demo and hear how people are doing it. This is not only good to level up your skills, but the skills of the person giving the call or demo as you give them honest but kind feedback.
* [ ] Sign up for the next online [GitHub Training](https://services.github.com/#upcoming-events) class, or [watch a previously recorded session](https://resources.github.com/webcasts/), OR go through some/all of the [on demand training](https://services.github.com/on-demand/).
  * Go to the #services room in chat and ping anyone there to send you the GoToWebinar registration link to attend for free or receive a link for a previous training
* [ ] Tell us what tools, services, and programming languages you have knowledge about in our [skills table](https://github.com/github/solutions-engineering/blob/SvanBoxel-skills/team/skills.md)
  
### Required activity
- [ ] Complete the Challenger eLearning exercise to dive a bit deeper by logging into the [Challenger Skill Development eLearning portal](https://challenger.myabsorb.com/#/login). See login instructions below. The exercise takes approximately 4 hours. _Optional:_ If you would like a refresher on Challenger, watch [this video prior](https://cebsaleseffectiveness.hubs.vidyard.com/watch/31sXSsbnsPsWqViXolDpTA) to getting started. <br>
**Login instructions:** 
     * You should have received an introductory email from noreply@myabsorb.com prompting you to log in. Please use the link within 7 days of receiving the email.
     * Your username to log in will be your email and the password of your choice after your initial log in.
     * If you have issues accessing the portal, please email activation@challengerinc.com to reset your account.

### Guides pt. 2
* [ ] [The Sales Guide](https://github.com/github/sales/tree/master/guide) - The manual for how the Sales team operates. Pay special attention to the following:
  * [ ] [github/sales "How We Work"](https://github.com/github/sales/blob/master/guide/how-we-work.md)  
  * [ ] [github/sales "Culture"](https://githubber.com/article/crafts/sales/sales-guide/sales-process/sales-culture)
  * [ ] [github/sales "Voice"](https://githubber.com/article/crafts/sales/sales-guide/sales-tools/writing-best-practices)
  * [ ] [github/sales "ChatOps"](https://githubber.com/article/crafts/sales/sales-guide/sales-process/Sales-Tools/Chatops)
* [ ] [Enterprise Help Docs and Guides](https://help.github.com/enterprise/)
* [ ] [Internal Amazon Web Services (AWS) guide](https://github.com/github/solutions-engineering/blob/master/guides/amazon-aws/aws-sales-guide.md)

### Git and GitHub Training
* [ ] [The Git Website](http://git-scm.com/) for general documentation knowledge.
* [ ] For an introduction to Git, play [Try Git](https://try.github.io/levels/1/challenges/1)
* [ ] Here's another beginner tutorial for Git: [Git-it (Desktop Version)](https://github.com/jlord/git-it-electron#what-to-install)
* [ ] For a more in depth tutorial on Git, play [GitHug](https://github.com/Gazler/githug)
* [ ] Familiarize yourself with [Octodemo](https://octodemo.com). This is the internal GitHub Enterprise instance the solutions engineer team uses for customer demos.
  - Create a repo, add a file to your repo, and create a pull request. (cc your buddy to make this more complete)
* [ ] View the [Integration playlist on YouTube](https://www.youtube.com/playlist?list=PLg7s6cbtAD16MZFt8waA38gATo5jxcDEp).
* [ ] [Resources on services.github.com](http://services.github.com/resources/videos/)
* [ ] [Learn Git Branching](http://pcottle.github.io/learnGitBranching/)  

### Preparing to Demo
* [ ] Watch at least two different demos on Vimeo. [Search the SE repo for issues mentioning vimeo to get links](https://github.com/github/solutions-engineering/issues?utf8=%E2%9C%93&q=vimeo.com) (Keep in mind, there have been different features developed over time that may not have been available during the demos!)
  - [Demo for Citi](https://vimeo.com/131761442/) (password: citi)
  - [Demo for Toyota Financial Services](https://vimeo.com/132893090/) (password: tfsdemo)
  - [Demo for Redbull](https://vimeo.com/152351621/) (password: github-redbull)
  - [Demo for The Onin Group](https://vimeo.com/139379187) (password: monalisa)
* _Optional:_
  * Follow the [demo prep guide](https://github.com/github/solutions-engineering/blob/master/guides/onboarding/preparing-to-demo.md) to get set up for your first demo.
  * Record your first demo for the team (see demo guide at https://github.com/github/solutions-engineering/tree/master/guides/demo)

### Cultural things to make sure you've mastered
* emoji  - see [emoji cheat sheet](http://www.emoji-cheat-sheet.com/), [emoji search](http://emoji.muan.co/), or type ":" in chat
* animated gifs [see them all](http://giphy.com)
* Chat basics, plain text paste, `.enterprise me`, `.who is <USERNAME>`, `.pug bomb`, `.quote`, `.sforce`, etc.
- [ ] **Understand and master**
  - `.rem | <PHRASE>` to search for phrase
  - `.canned <PHRASE>` to search our [canned replies](https://github.com/github/sales/blob/master/resources/canned-replies.md). This is super helpful for answering most sales questions
  - `.secq <PHRASE>` to serach our [Security FAQs](https://github.com/github/knowledge-base/blob/master/security/FAQ/FAQ.md)

### Sales resources
* [github/sales "resources"](https://github.com/github/sales/tree/master/resources) (lots of reusable goodies including canned replies and infosec questionairre responses)
* [General Enterprise Sales Process](https://github.com/github/sales/blob/master/guide/process-guides/README.md)
* [Understanding our market and competitors](https://githubber.com/category/crafts/sales/sales-guide/competition)
* [github/sales staffing and territories](https://github.com/github/sales/tree/master/territory-management)
  * [AMEA](https://github.com/github/sales/blob/master/territory-management/Alignment%20Matrix%20-%20AMER.md)
  * [APAC](https://github.com/github/sales/blob/master/territory-management/Alignment%20Matrix%20-%20APAC.md)
  * [EMEA](https://github.com/github/sales/blob/master/territory-management/Alignment%20Matrix%20-%20EMEA.md)
* [ ] [Sales Issue Discussions](https://github.com/github/sales/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Adiscussion)
* [ ] [Pricing](https://githubber.com/article/crafts/sales/sales-guide/sales-process/discount-approval)
* [ ] [Licensing](https://githubber.com/article/crafts/sales/sales-guide/pricing-and-licensing/license-types)

### Company resources
* [ ] [tl;dr](https://pages.ghe.io/tldr/) - Too long; didn't read. Summary from around the company that also comes in an email once a week.
* [ ] [GitHub Engineering Blog](http://githubengineering.com/) - A periodically updated blog from GitHub engineers that primarily covers our engineering culture and projects.
* [ ] [GitHub external blog](https://blog.github.com) - GitHub's public blog where we announce all sorts of goodness including new features, breaking changes, and community events.

#### Other teams we work closely with
* `@github/services` handles both training and implementation engagements. Mention `@github/services-training` for training-specific questions, and `@github/services-engineers` for implementation. If unclear, fall back to `@github/services`.
* `@github/sales` is the catch-all for everyone on the Sales team, including Solutions Engineers. Mention `@github/sales-csm`, `@github/sales-corporate`, `@github/sales-development` or `@github/sales-enterprise` for a specific Sales team. `@github/sales-emea` will get you the Sales team in Europe.
* `@github/enterprise-support` helps our customers with support queries related to GitHub Enterprise
* [`@github/enterprise-on-prem`](https://github.com/orgs/github/teams/enterprise-on-prem) and [`@github/enterprise-on-prem-product`](https://github.com/orgs/github/teams/enterprise-on-prem-product) teams are responsible for building and maintaining the GitHub Enterprise product
* [`@github/enterprise-quality`](https://github.com/orgs/github/teams/enterprise-quality) does automated and manual testing of GitHub Enterprise
* `@github/ar` handles AR, and works closely with us. Any invoice issues or vendor registration needs should involve her.
* `@github/legal` is how to get a hold of our legal team, open issues to review legal changes in the [legal-review repo](https://github.com/github/legal-review)
* `@github/finance` handles AP, and is responsible for expense reports and gettin you :moneybag:

### Bonus reads and resources
* [Orwells Rules of Effective Writing](http://www.pickthebrain.com/blog/george-orwells-5-rules-for-effective-writing/)
* Paul Ford's ["What is Code?"](http://www.bloomberg.com/graphics/2015-paul-ford-what-is-code/) article
* [Competitive Analysis/Explanation of GitSwarm (by PM at Perforce)](https://www.quora.com/What-is-the-real-story-between-GitSwarm-and-GitLab)  
* [Perforce Article: Achieving Secure DevOps](https://www.perforce.com/resources/webinars/achieving-secure-devops-overcoming-risks-modern-service-delivery)  
* [Overview of TFS](https://www.visualstudio.com/en-us/products/tfs-overview-vs.aspx)  
* [Add access token for command line access over HTTPS](https://github.com/blog/1614-two-factor-authentication#how-does-it-work-for-command-line-git)
* [Caching GitHub password for command line access](https://help.github.com/articles/caching-your-github-password-in-git/) 
* [GitHub, A Beginner's Journey](http://readwrite.com/2013/09/30/understanding-github-a-journey-for-beginners-part-1)  

### Tools and Services: Miscellaneous
These tools are optional. Install if you find them useful.
* [ ] [TextExpander](http://smilesoftware.com/TextExpander/index.html) for fast-insertion of common responses or phrases, license in [Gear](https://gear.githubapp.com/apps).
  * **NOTE:** If you do install TextExpander, be sure to enable Secure Input by following these [instructions](https://gist.github.com/bryancross/df3b5046670bb702574ec7fc04ff8b19)
* [Monosnap](https://www.monosnap.com/welcome) or [Annotate](https://itunes.apple.com/us/app/annotate-capture-and-share/id918207447?mt=12) for screenshotting. Alternatively, [reconfigure the keyboard shortcuts](https://cloud.githubusercontent.com/assets/700173/9878779/bcdef198-5bc4-11e5-9b41-9ffd2e4c22ba.png) to make screenshotting in OSX easier
* [ ] [Presentation Fonts](https://github.com/github/keynote/tree/master/fonts#fonts) (Apex New is the main type face, but many others exist)
* [ ] VMware Fusion [Available at VMWare](http://www.vmware.com/products/fusion-pro), license in [Gear](https://gear.githubapp.com/apps).
* Mouseposè
* [ ] Setup [enterprise-crypto](https://github.com/github/enterprise-crypto). This tool will be useful later on to check the details of GitHub Enterprise license keys.
* [ ] [Licecap](http://www.cockos.com/licecap/) - best tool for quickly recording animated GIFs of your screen.
* [ ] [Moom](https://manytricks.com/moom/) or [Spectacle](https://www.spectacleapp.com/) - easily rearrange windows in OSX

### More fun stuff

* [ ] Review [working with security questionnaires](https://github.com/github/solutions-engineering/blob/master/guides/internal-tools/working_with_security_questionnaires.md) and get access to shared [Security Questionnaires folder](https://drive.google.com/drive/folders/0BzGOJmkt0vlTUmY0YkhCT0tRVzA) in Google Drive. @mention your buddy to grant you write access.
* .enterprise me (funny stuff from customers, also .enterprise remember <funnystuff>)
* Follow `@githubstatus` on [Twitter](https://twitter.com/githubstatus)
